server:
  port: 8761

spring:
  application:
    name: Discovery-Server

--- # eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: ${EUREKA_HOST:localhost}
